### ISSUE TITLE
Expose animation speed parameter for reconstructing destructibles

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#18]
Allow designers to tweak the speed of animation (curve is preferred eg fast and start and much slower at the end)

**Comment by scarletoath** [comment]
This is already exposed on the DestructibleCover component.

**Comment by smkrexus** [comment]
Need interpolated values for anim speed over period of time
Currently the value given is time, will need additional control of anim speed at start vs end

**Values needed**
Anim Speed at Start
Anim Speed at end
Target Rebuild Duration (already exist)

**Comment by smkrexus** [comment]
Keyframe perimeters after first keyframe do not work using design branch ee8850da
Updated explosive barrel with test parameters Obstacle_Destructible_ExplosiveBarrel_1m

**Comment by smkrexus** [comment]
Verified on 3bc3e7e6.
Works occasionally, still KIV, will open again if necessary
