### ISSUE TITLE
Unable to trigger destruction animation for explosive barrel

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#22]
Cant tell if the destructible animation is not set up properly or some component is not set up
Player still loses health upon hitting it so something must have already been set up

**Comment by RemusW** [comment]
thought I fixed this a while ago, the static geo keeps getting unhooked from the script

**Comment by scarletoath** [comment]
Probably meta file conflict issue (you assign it based on your meta files, but someone else has that filename with a different GUID, so it loses the ref since Unity tracks assets via GUID).

**Comment by smkrexus** [comment]
Verified on design branch ee8850da
