### ISSUE TITLE
Enemy death explosion always shows inverted explosion visuals

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#25]
Notice that killing enemies will always result in a blue explosion, regardless of the enemy's actual state

**Comment by weiiiiii** [comment]
![image](https://user-images.githubusercontent.com/27207632/108031937-9e53c100-706c-11eb-9316-3e570a4c459e.png)
IsForward by default is false.

**Comment by smkrexus** [comment]
Verified in 6174ec61
