### ISSUE TITLE
Destructible objects retain original collision in destroyed state

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#27]
Destructible objects should not retain its original collision in destroyed state.
This results in invisible blocking of player movement and bullets 

Should have additional option to set collisions based on its state

**Comment by scarletoath** [comment]
Move the colliders to the individual state objects and they will be automatically handled as part of changing active state object.

**Comment by smkrexus** [comment]
Fixed and verified on 10bf6f9d
