### ISSUE TITLE
Missing (deleted) prefabs causing object leaks in Gym_Tiles scene

### ISSUE THREAD

**Issue by scarletoath** [scarletoath/GGJ2021-TenetCB#28]
Unity auto-creates a "Recovery" GameObject for each Transform associated with a missing prefab. Seems to be compounded if the scene is repeatedly saved.

The prefab instances with missing prefabs should be cleaned up to prevent further leaks.
![image](https://user-images.githubusercontent.com/1894141/107818248-f4f38f00-6d3c-11eb-84be-f06e1b639646.png)

**Comment by smkrexus** [comment]
Fixed in 6d7cbe0c
