### ISSUE TITLE
Bullet does not travel to intended location when aiming towards the ground at close range

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#31]
![image](https://user-images.githubusercontent.com/78133127/107868652-0cf41b80-6ec1-11eb-82a7-31d3cd124bb7.png)

Notice that aiming towards the ground and shooting will cause a history marker to be created at the bullet spawn point rather than the ground

**Comment by scarletoath** [comment]
Was not really able to repro this anymore after some previous fixes, but just fixed the layers anyway.

**Comment by smkrexus** [comment]
Verified on 154defa3
