### ISSUE TITLE
Main Menu tiles does not spawn anything

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#32]
![image](https://user-images.githubusercontent.com/78133127/107887592-1bcee280-6f42-11eb-994b-9cf92a49e0fb.png)
Notice that the tiles do not spawn anything thorughout the flybys, the same tiles are used in test scene and it works properly

**Comment by scarletoath** [comment]
Oh I bet this has to do with the deterministic random seed I just added.

**Comment by smkrexus** [comment]
Verified in ec2bda56
