### ISSUE TITLE
[EDITOR] Gym_Tiles is extremely laggy when all the tiles are shown

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#4]
Gym_Tiles experiencing lag when showing all tiles
This happened after the destructibles were updated to contain the visual of the destroyed mesh
Makes it difficult to work in Gym_Tiles

**Comment by scarletoath** [comment]
Looks like it is related to destructible objects.

**Comment by smkrexus** [comment]
Still same amount of lag as before.
Enable layers of all tileobjects will cause it to be very laggy

**Comment by smkrexus** [comment]
certain tileobjects groups seem to be laggier than others, inversion rooms seem ok, while landmarks / ambush etc. seem more laggy

**Comment by scarletoath** [comment]
The editor view is fixed. Hide your game view/disable game player for editor to work fine.

**Comment by smkrexus** [comment]
Verified on c433387a
