### ISSUE TITLE
Decal Projector may project in front opaque objects

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#43]
![image](https://user-images.githubusercontent.com/78133127/109032396-921cd300-7700-11eb-82f3-0df6607a3ad4.png)
Notice that the decals may be able to be seen through opaque objects in front of it, even though it is well outside of projection range.

Seed: 999117205

![image](https://user-images.githubusercontent.com/78133127/109035016-30119d00-7703-11eb-9ee8-111e8e374386.png)
Seed: -1117350231

**Comment by scarletoath** [comment]
Tested in both main 6174ec61 and design 8e239fc9
