### ISSUE TITLE
[AI] Enemy visuals does not rotate towards player

### ISSUE THREAD

**Issue by smkrexus** [scarletoath/GGJ2021-TenetCB#8]
Notice that any linked meshes (apart from the weapon) do not rotate towards the player

**Comment by smkrexus** [comment]
enemey_robot can be used as enemy mesh

**Comment by weiiiiii** [comment]
Just tested that, seems to be an animation

**Comment by weiiiiii** [comment]
![image](https://user-images.githubusercontent.com/27207632/108216382-61232800-716d-11eb-914c-d8335a830a69.png)
Note that mesh is added as a child object under enemy.

**Comment by smkrexus** [comment]
Verified in 6174ec61
